### ISSUE TITLE
Clarify MAINTAINERS post OCI move

### ISSUE THREAD

**Issue by caniszczyk** [opencontainers/go-digest#15]
Who will be the official list of maintainers @stevvooe ?

**Comment by stevvooe** [comment]
The [official list is here](https://github.com/opencontainers/tob/pull/22/files#diff-50c1a61835539e3b113a3707327d0a06R17):

* Brandon Philips <brandon.philips@coreos.com> (@philips)
* Brendan Burns <bburns@microsoft.com> (@brendandburns)
* Jason Bouzane <jbouzane@google.com> (@jbouzane)
* John Starks <jostarks@microsoft.com> (@jstarks)
* Jonathan Boulle <jon.boulle@coreos.com> (@jonboulle)
* Stephen Day <stephen.day@docker.com> (@stevvooe)
* Vincent Batts <vbatts@redhat.com> (@vbatts)

I think there may have been a stipulation to allow any of the members of this list to decline maintainership.

**Comment by caniszczyk** [comment]
I will add everyone now to the @opencontainers/go-digest-maintainers group and give people until Friday if they want to back out of being a maintainer for this repo.

**Comment by stevvooe** [comment]
@caniszczyk Close this?

**Comment by caniszczyk** [comment]
@stevvooe SGTM, if any of the @opencontainers/go-digest-maintainers please state on this issue otherwise hold your peace :)
