### ISSUE TITLE
Ship a release!

### ISSUE THREAD

**Issue by caniszczyk** [opencontainers/go-digest#23]
Currently there are no tags/releases :)

https://github.com/opencontainers/go-digest/releases

**Comment by stevvooe** [comment]
@caniszczyk Assuming this release is administrative. Created https://github.com/opencontainers/go-digest/milestone/1.

**Comment by caniszczyk** [comment]
LGTM

**Comment by stevvooe** [comment]
Release proposal here: https://groups.google.com/a/opencontainers.org/forum/#!topic/dev/f_iszYlOmpk.

**Comment by caniszczyk** [comment]
Awesome @stevvooe, looks like you have 6 votes of 9 (counting your implicit LGTM by proposing the vote)

**Comment by wking** [comment]
On Tue, Jan 31, 2017 at 06:36:24AM -0800, Chris Aniszczyk wrote:
> (counting your implicit LGTM by proposing the vote)

If folks want to document that implicit LGTM, I've floated some
wording in opencontainers/project-template#18.  I think it just needs
an OCI maintainer interested enough to launch a project-templaet vote.

**Comment by vbatts** [comment]
@caniszczyk and @stevvooe this project is still copyright to Docker, Inc. Does that change with it being donated to OCI?

**Comment by vbatts** [comment]
well, more confusing than that. The README.md, LICENSE.code and the source *.go cite Docker Inc; the CONTRIBUTING cites Linux Foundation.

**Comment by runcom** [comment]
CONTRIBUTING.md still refers to Docker also https://github.com/opencontainers/go-digest/blob/master/CONTRIBUTING.md#contributing-to-docker-open-source-projects

**Comment by caniszczyk** [comment]
@vbatts Copyright is retained by the contributor, similar to how the Kernel works as an example. There's no requirement to change it unless we wanted to do copyright assignment but that's not really required.

Furthermore, here's no requirement of assignment of copyright to OCI/LF, all the OCI IP policy cares about (section 8: https://www.opencontainers.org/about/governance) is 

> "All new inbound contributions to OCI will be made under the Apache License, Version 2.0 (available at http://www.apache.org/licenses/LICENSE-2.0) accompanied by a Developer Certificate of Origin sign-off (http://developercertificate.org). All contributions by Member employees will bind their employers in accordance with this policy, including the patent and copyright license grants in the Apache License, Version 2.0."

**Comment by caniszczyk** [comment]
Honestly, for projects that have a history to them, we should probably be doing "Copyright [original contributor] and Open Container Initiative Contributors" something to that nature

So in this case, "Copyright Docker, Inc. and Open Container Initiative Contributors"

**Comment by wking** [comment]
> So in this case, "Copyright Docker, Inc. and Open Container Initiative Contributors"

Sort of [like this][1]?

[1]: https://github.com/opencontainers/go-digest/pull/20/files#diff-04c6e90faac2675aa89e2176d2eec7d8R95

**Comment by vbatts** [comment]
@caniszczyk thanks for the info. I wasn't clear.

**Comment by stevvooe** [comment]
@caniszczyk Closing this. We'll switch milestones from here on out.
