### ISSUE TITLE
Failed while installing

### ISSUE THREAD

**Issue by seenureddy** [opencontainers/go-digest#39]
I was trying to install using the glide. Got this error:

` Fetching github.com/opencontainers/go-digest
[INFO]	--> Setting version for github.com/opencontainers/go-digest to a6d0ee40d4207ea02364bd3b9e8e77b9159ba1eb.
[ERROR]	Failed to retrieve a list of dependencies: Error resolving imports
`

**Comment by dmcgowan** [comment]
This library has no non-standard library imports and no main binary to install. This seems like an issue with glide or the glide configuration.

**Comment by seenureddy** [comment]
@dmcgowan  I was using the glide 13.2 version in my machine.
