### ISSUE TITLE
Document digest specification?

### ISSUE THREAD

**Issue by wking** [opencontainers/go-digest#6]
There are already some docs for the [very-closely-related OCI digests][1], but if this spec wants to keep mixed-case hashes around (#3), it's probably worth documenting the local choices independently.  For example, is there a way to identify hex hashes vs. base64 hashes (counting characters and comparing with the algorithm's hash size?)?  Are *hex* hashes allowed to be mixed case?  We probably don't want to dig into those ambiguities in this issue, I'm just asking maintainers if they plan on providing a specification for the digests that this package will parse/generate.

[1]: https://github.com/opencontainers/image-spec/blob/v1.0.0-rc3/descriptor.md#digests-and-verification

**Comment by stevvooe** [comment]
@wking I think we can add a reference to Docker Registry HTTP API V2 and OCI Image Spec.

Encoding is a different issue. Basically, it is a per-alg detail. The addition of alt encoding schemes isn't a part of this package. In practice, this hasn't been an issue but we may want to narrow this package's validation.

Let me update this in the ecosystem before getting too deep here.

**Comment by stevvooe** [comment]
After some thought, it is best that this package supports a superset of what is valid in the OCI specification. This package will validate the minimum safe level of digest format. Anything further than that can be done in the specification specific validator.

Thank you for you submission!
